# Generated by Django 2.2.5 on 2019-10-02 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='StudentBotUser',
        ),
    ]
