# Generated by Django 2.2.5 on 2019-10-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20191002_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbotuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='studentbotuser',
            name='phone_number',
            field=models.CharField(default=1, max_length=264),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentbotuser',
            name='email',
            field=models.CharField(max_length=128),
        ),
    ]
